MyFinance/Controllers/PlanoContaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyFinance.Models;

namespace MyFinance.Controllers
{
    public class PlanoContaController : Controller
    {


        IHttpContextAccessor HttpContextAccessor;


        //Recebe o contexto p/ variaveis de Sessao
        public PlanoContaController(IHttpContextAccessor httpContextAccessor)
        {
            HttpContextAccessor = httpContextAccessor;
        }

        //Metodo Listar Plano de Contas
        public IActionResult Index()
        {
            //CRIA UM OBJETO CONTA
            PlanoContasModel objPlanoContas = new PlanoContasModel(HttpContextAccessor);
            // LISTA O OBJETO CONTA E PASSA PAA VIEW - ATRAVEZ DO (ViewBag)
            ViewBag.ListaPlanoContas = objPlanoContas.ListaPlanoContas();
            return View();
        }





        // VALIDA CAMPOS VAZIOS DO FORMULARIO 
        [HttpGet]
        public IActionResult CriarPlanoConta(int? id)
        {

            if (id != null)
            {
                //CRIA UM OBJETO CONTA
                PlanoContasModel objPlanoContas = new PlanoContasModel(HttpContextAccessor);
                // LISTA O OBJETO CONTA E PASSA PAA VIEW - ATRAVEZ DO (ViewBag)
                ViewBag.Registro = objPlanoContas.CarregarRegistro(id);
            }
            return View();
        }


        // Insert Conta
        [HttpPost]
        public IActionResult CriarPlanoConta(PlanoContasModel planoContasModel)
        {

            if (ModelState.IsValid)
            {
                //PEGA USUARIO DA SESSÃO
                planoContasModel.HttpContextAccessor = HttpContextAccessor;

                planoContasModel.Insert();
                return RedirectToAction("Index");

            }
            return View();
        }







        [HttpGet]
        public IActionResult ExcluirPlanoConta(int id)
        {

            PlanoContasModel objPlanoContas = new PlanoContasModel(HttpContextAccessor);
            objPlanoContas.Excluir(id);
            return RedirectToAction("Index");
        }




    }

}

MyFinance/Views/PlanoConta/CriarPlanoConta.cshtml
@model PlanoContasModel


@{ 
    var vId = 0;
    var vDescicao = "";
    var vTipo = "";

    try
    {

        vId = int.Parse(@ViewBag.Registro.Id.ToString());
        vDescicao = @ViewBag.Registro.Descricao.ToString();
        vTipo = @ViewBag.Registro.Tipo.ToString();
    }
    catch 
    {
      
    }

}

<h2>Criar Plano Conta</h2>

<form asp-controller="PlanoConta" asp-action="CriarPlanoConta">
    <input type="hidden" asp-for="Id" value="@vId"/>
    <div>
        <label>Nome</label>
        <input type="text" class="form-control" asp-for="Descricao" value="@vDescicao"/>
        <span asp-validation-for="Descricao" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label>Tipo</label>

        @{


            if (vTipo == "R")
            {
                <div class="radio"><label><input type="radio" asp-for="Tipo" value="R" checked />Receita</label></div>
                <div class="radio"><label><input type="radio" asp-for="Tipo" value="D" unchecked />Despesa</label></div>

            }
            else
            {
                <div class="radio"><label><input type="radio" asp-for="Tipo" value="R" unchecked />Receita</label></div>
                <div class="radio"><label><input type="radio" asp-for="Tipo" value="D" checked />Despesa</label></div>

            }


        }


    </div>

    <br />


    <button type="submit" class="btn btn-success">Salvar</button>
    <button type="reset" class="btn ">Cancelar</button>
</form>

MyFinance/Views/PlanoConta/Index.cshtml
<!--
    View Listar Plano de Contas
-->



@{
    ViewData["Title"] = "Index";
}

<h2>Plano Contas</h2>

<br />
<div class="row">
    <div class="col-lg-6">
        <button class="btn btn-success" onclick="criarPlanoConta()"> <strong>+</strong> Adicionar Conta</button>
    </div>

    <div class="col-lg-6">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
                <button class="btn btn-default" type="button">Go!</button>
            </span>
        </div>
    </div>
</div>

<br /><br />

<table class="table table-bordered">
    <thead>
        <tr>

            <th style="width:20px"> <strong>#ID</strong></th>
            <th>Descrição</th>
            <th>Tipo</th>
            <th>Ações</th>
        </tr>
    </thead>

    @{
        foreach (var item in (List<PlanoContasModel>)ViewBag.ListaPlanoContas)
        {
            <tbody>
                <tr>
                    <td> @item.Id.ToString()</td>
                    <td>@item.Descricao.ToString()</td>
                    <td>@item.Tipo.ToString().Replace("R", "Receita").Replace("D", "Despesa")</td>
                    <td>
                        <button type="button" class="btn btn-warning">Ver</button>
                        <button class="btn btn-primary" onclick="editarPlanoConta(@item.Id.ToString())">Editar</button>
                        <button class="btn btn-danger" onclick="ExcluirPlanoConta(@item.Id.ToString())">Excluir</button>
                    </td>
                </tr>
            </tbody>

        }
    }
</table>

<script>
    function criarPlanoConta() {
        window.location.href = "../PlanoConta/CriarPlanoConta";

    }

    function ExcluirPlanoConta(id_conta) {
        window.location.href = "../PlanoConta/ExcluirPlanoConta/" + id_conta;

    }

    function editarPlanoConta(id_conta) {
        window.location.href = "../PlanoConta/CriarPlanoConta/" + id_conta;

    }

</script>