MyFinance/Controllers/ContaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyFinance.Models;

using Rotativa.AspNetCore;

using PagedList;


namespace MyFinance.Controllers
{
    public class ContaController : Controller
    {
        IHttpContextAccessor HttpContextAccessor;

        //Recebe o contexto p/ variaveis de Sessao
        public ContaController(IHttpContextAccessor httpContextAccessor)
        {
            HttpContextAccessor = httpContextAccessor;
        }


        public IActionResult Index()
        {
            //CRIA UM OBJETO CONTA
            ContaModel obConta = new ContaModel(HttpContextAccessor);
            // LISTA O OBJETO CONTA E PASSA PAA VIEW - ATRAVEZ DO (ViewBag)
            ViewBag.listaConta = obConta.ListaConta();

            //var listaConta = obConta.ListaConta();


           
                //Definindo a paginação              
            

                return View();

           
        

    }   

        // VALIDA CAMPOS VAZIOS DO FORMULARIO 
        [HttpGet]
        public IActionResult CriarConta()
        {

            return View();
        }


        // Insert Conta
        [HttpPost]
        public IActionResult CriarConta(ContaModel contaModel)
        {

            if (ModelState.IsValid)
            {
                //PEGA USUARIO DA SESSÃO
                contaModel.HttpContextAccessor = HttpContextAccessor;

                contaModel.Insert();
                return RedirectToAction("Index");

            }
            return View();
        }

        [HttpGet]
        public IActionResult ExcluirConta(int id)
        {

            ContaModel obConta = new ContaModel(HttpContextAccessor);
            obConta.Excluir(id);
            return RedirectToAction("Index");
        }




    }
}

MyFinance/Views/Conta/CriarConta.cshtml
@model ContaModel

@{
    ViewData["Title"] = "CriarConta";
}

<h2>Criar Nova Conta</h2>

<form asp-controller="Conta" asp-action="CriarConta">
    <div>
        <label>Nome</label>
        <input type="text" class="form-control" asp-for="Nome" />
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>

    <div>
        <label>Saldo</label>
        <input type="text" class="form-control" asp-for="Saldo" />
        <span asp-validation-for="Saldo" class="text-danger"></span>
    </div>

    <br />

    
    <button type="submit" class="btn btn-success">Salvar</button>
    <button type="reset" class="btn ">Cancelar</button>
</form>

MyFinance/Views/Conta/Index.cshtml
<!--
    View Listar Contas
-->

@using PagedList.Core.Mvc





<h2>Listar Contas</h2>
<br />
<div class="row">
    <div class="col-lg-6">
        <button class="btn btn-success" onclick="criarConta()"> <strong>+</strong> Adicionar Conta</button>
    </div>

    <div class="col-lg-6">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
                <button class="btn btn-default" type="button">Go!</button>
            </span>
        </div>
    </div>
</div>

<br /><br />

<table class="table table-bordered">
    <thead>
        <tr>

            <th style="width:20px"> <strong>#ID</strong></th>
            <th>Nome</th>
            <th>Saldo</th>
            <th>Ações</th>
        </tr>
    </thead>

    @{
        foreach (var item in (List<ContaModel>)ViewBag.ListaConta)
        {
            <tbody>
                <tr>
                    <td> @item.Id.ToString()</td>
                    <td>@item.Nome.ToString()</td>
                    <td>R$ @item.Saldo.ToString()</td>
                    <td>
                        <button type="button" class="btn btn-warning">Ver</button>
                        <button class="btn btn-primary">Editar</button>
                        <button class="btn btn-danger" onclick="ExcluirConta(@item.Id.ToString())">Excluir</button>
                    </td>
                </tr>
            </tbody>

        }
    }
</table>



<script>
    function criarConta() {
        window.location.href = "../Conta/CriarConta";

    }

    function ExcluirConta(id_conta) {
        window.location.href = "../Conta/ExcluirConta/" + id_conta;

    }
</script>