MyFinance/Controllers/TransacaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyFinance.Models;

namespace MyFinance.Controllers
{
    public class TransacaoController : Controller
    {

        IHttpContextAccessor HttpContextAccessor;

        //Recebe o contexto p/ variaveis de Sessao
        public TransacaoController(IHttpContextAccessor httpContextAccessor)
        {
            HttpContextAccessor = httpContextAccessor;
        }

        //Metodo Listar Plano de Contas
        public IActionResult Index()
        {
            //CRIA UM OBJETO CONTA
            TransacaoModel objTransacao = new TransacaoModel(HttpContextAccessor);
            // LISTA O OBJETO CONTA E PASSA PAA VIEW - ATRAVEZ DO (ViewBag)
            ViewBag.ListaTransacao = objTransacao.ListaTransacao();
            return View();
        }


        // VALIDA CAMPOS VAZIOS DO FORMULARIO 
        [HttpGet]
        public IActionResult Registrar(int? id)
        {

            if (id != null)
            {
                
                TransacaoModel objTransacao = new TransacaoModel(HttpContextAccessor);
                ViewBag.Registro = objTransacao.carregarRegistro(id);

            }
            ViewBag.ListaContas = new ContaModel(HttpContextAccessor).ListaConta();
            ViewBag.ListaPlanoConta = new PlanoContasModel(HttpContextAccessor).ListaPlanoContas();
            return View();
        }



        [HttpPost]
        public IActionResult Registrar(TransacaoModel transacaoModel)
        {
            if (ModelState.IsValid)
            {
                //PEGA USUARIO DA SESSÃO
                transacaoModel.HttpContextAccessor = HttpContextAccessor;

                transacaoModel.Insert();
                return RedirectToAction("Index");

            }
            return View();
        }





        [HttpGet]
        public IActionResult ExcluirTransacao(int id)
        {

            TransacaoModel objPlanoContas = new TransacaoModel(HttpContextAccessor);
            objPlanoContas.Excluir(id);
            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult DetalhesTransacao(int id)
        {

           
            TransacaoModel objTransacao = new TransacaoModel(HttpContextAccessor);
            ViewBag.Registro = objTransacao.carregarRegistro(id);
            return View();

        }




        [HttpGet]
        [HttpPost]
        public IActionResult Extrato(TransacaoModel transacaoModel)
        {
            transacaoModel.HttpContextAccessor = HttpContextAccessor;
            ViewBag.ListaTransacao = transacaoModel.ListaTransacao();

            ViewBag.ListaContas = new ContaModel(HttpContextAccessor).ListaConta();

            return View();
        }


        public IActionResult Grafico()
        {

            List<Dashboard> lista = new Dashboard().RetornarDadosGraficoPie();

            string valores = "";
            string labels = "";
            string cores = "";

            var random = new Random();

            for (int i = 0; i < lista.Count; i++)
            {
                valores += lista[i].Total.ToString() + ",";
                labels += "'" + lista[i].PlanoConta.ToString() + "',";
                cores += "'" + String.Format("#{0:x6}", random.Next(0x1000000)) + "',";

            }
            //ViewBag.Cores  = "'#cecece', '#465789', '#fff125', '#784586', '#504030'";

            ViewBag.Cores = cores;
            ViewBag.Labels = labels;
            ViewBag.Valores = valores;
            return View();
        }
    }
}

MyFinance/Views/Transacao/DetalhesTransacao.cshtml
<!-- Modal Detalhes-->
<div id="modalDetalhes" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Detalhes do Registo</h4>
            </div>
            <div class="modal-body">
                <p>@ViewBag.ListaTransacao.Id.ToSting()</p>
                <p></p>


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

MyFinance/Views/Transacao/Extrato.cshtml
@model TransacaoModel

<h2>Extrato</h2>

<div class="container">
    <form asp-controller="Transacao" asp-action="Extrato">
        <div class="form-group">
            <label>Data Transação Inicio</label>
            <input type="date" asp-for="Data" class="form-control" />
        </div>

        <div class="form-group">
            <label>Data Transação Final</label>
            <input type="date" asp-for="DataFinal" class="form-control" />
        </div>

        <div class="form-group">
            <label>Tipo Transação</label>
            <div class="radio"> <label><input type="radio" asp-for="Tipo" value="A" checked>Receitas e Despesas  </label></div>
            <div class="radio"> <label><input type="radio" asp-for="Tipo" value="R">Receitas  </label></div>
            <div class="radio"> <label><input type="radio" asp-for="Tipo" value="D">Despesas  </label></div>
        </div>

        <div class="form-group">
            <label>Conta</label>
            <select asp-for="Conta_Id" class="form-control">
                @{
                    foreach (var item in (List<ContaModel>)ViewBag.ListaContas)
                    {
                        <option value="@item.Id.ToString()">@item.Nome.ToString()</option>
                    }
                }
            </select>
        </div>
        <button type="submit" class="btn btn-block btn-success">Filtrar</button>
    </form>
</div>

<br />

<table class="table table-bordered">
    <thead>
        <tr>

            <th style="width:20px"> <strong>#ID</strong></th>
            <th>Data</th>
            <th>Tipo</th>
            <th>Valor</th>
            <th>Historico</th>
            <th>Conta</th>
            <th>Plano de Contas</th>
            
        </tr>
    </thead>

    @{
        var TotalReceitas = 0.0;
        var TotalDespesas = 0.0;
        var vSaldo = 0.0;

        foreach (var item in (List<TransacaoModel>)ViewBag.ListaTransacao)
        {
            <tbody>
                <tr>
                    <td> @item.Id.ToString()</td>
                    <td>@item.Data.ToString()</td>
                    <td>@item.Tipo.ToString().Replace("R", "Receita").Replace("D", "Despesa")</td>
                    <td>@item.Valor.ToString()</td>
                    <td>@item.Descricao.ToString()</td>
                    <td>@item.NomeConta.ToString()</td>

                    <td>@item.DescricaoPlanoConta.ToString()</td>

                    @{ 
                        if (item.Tipo == "D")
                        {
                            TotalDespesas  += double.Parse(item.Valor.ToString());

                        }
                        else
                        {
                            TotalReceitas  += double.Parse(item.Valor.ToString());

                        }
                    }

            </tbody>

                        }
                        vSaldo = TotalReceitas - TotalDespesas;
    }
</table>


<h3 style="background-color:brown"><strong>Saldo: </strong> R$ @vSaldo</h3>
<script>
    function Editar(id) {
        window.location.href = "../Transacao/Registrar/" + id;

    }
</script>

MyFinance/Views/Transacao/Grafico.cshtml
<h3>Grafico Pie</h3> <h4>Despesas</h4>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js"></script>


<div id="canvas-holder" style="width:70%">
    <canvas id="chart-area"></canvas>
</div>
<script>
    var randomScalingFactor = function () {
        return Math.round(Math.random() * 100);
    };

    var config = {
        type: 'pie',
        data: {
            datasets: [{
                data: [
                   @Html.Raw(ViewBag.Valores)
                ],
                backgroundColor: [
                  @Html.Raw(ViewBag.Cores)
                ],
                label: 'Dataset 1'
            }],
            labels: [
                 @Html.Raw(ViewBag.Labels)
            ]
        },
        options: {
            responsive: true
        }
    };

    window.onload = function () {
        var ctx = document.getElementById('chart-area').getContext('2d');
        window.myPie = new Chart(ctx, config);
    };

</script>




<title>Pie Chart</title>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js"></script>


<div id="canvas-holder" style="width:40%">
    <canvas id="chart-area"></canvas>
</div>
<script>
    var randomScalingFactor = function () {
        return Math.round(Math.random() * 100);
    };

    var config = {
        type: 'pie',
        data: {
            datasets: [{
                data: [
                    randomScalingFactor(),
                    randomScalingFactor(),
                    randomScalingFactor(),
                    randomScalingFactor(),
                    randomScalingFactor(),
                ],
                backgroundColor: [
                    window.chartColors.red,
                    window.chartColors.orange,
                    window.chartColors.yellow,
                    window.chartColors.green,
                    window.chartColors.blue,
                ],
                label: 'Dataset 1'
            }],
            labels: [
                'Red',
                'Orange',
                'Yellow',
                'Green',
                'Blue'
            ]
        },
        options: {
            responsive: true
        }
    };

    window.onload = function () {
        var ctx = document.getElementById('chart-area').getContext('2d');
        window.myPie = new Chart(ctx, config);
    };

</script>

MyFinance/Views/Transacao/Index.cshtml
<!--
    View Listar Transação
-->

@model TransacaoModel

<h2>Transações</h2>

<br />
<!-- -->
<div class="row">
    <div class="col-lg-6">
        <button class="btn btn-success" onclick="registrarTransacao()"> <strong>+</strong> Adicionar Conta</button>
    </div>

    <div class="col-lg-6">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
                <button class="btn btn-default" type="button">Go!</button>
            </span>
        </div>
    </div>
</div>
<!-- -->
<br /><br />

<table class="table table-bordered">
    <thead>
        <tr>

            <th style="width:20px"> <strong>#ID</strong></th>
            <th>Data</th>
            <th>Tipo</th>
            <th>Valor</th>
            <th>Historico</th>
            <th>Conta</th>
            <th>Plano de Contas</th>
            <th>Ação</th>
        </tr>
    </thead>

    @{
        foreach (var item in (List<TransacaoModel>)ViewBag.ListaTransacao)
        {
            <tbody>
                <tr>
                    <td> @item.Id.ToString()</td>
                    <td>@item.Data.ToString()</td>
                    <td>@item.Tipo.ToString().Replace("R", "Receita").Replace("D", "Despesa")</td>
                    <td>@item.Valor.ToString()</td>
                    <td>@item.Descricao.ToString()</td>
                    <td>@item.NomeConta.ToString()</td>

                    <td>@item.DescricaoPlanoConta.ToString()</td>

                    <td>
                        <button type="button" class="btn btn-warning" id="btDetalhes" onclick="DetalhesTransacao(@item.Id.ToString())">Ver</button>
                        <button class="btn btn-primary" onclick="editarTransacao(@item.Id.ToString())">Editar</button>
                        <button class="btn btn-danger" id="btDelete" onclick="ExcluirTransacao(@item.Id.ToString())">Excluir</button>
                    </td>
                </tr>
            </tbody>

        }
    }
</table>




<!-- Modal Excluir-->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Atenção</h4>
            </div>
            <div class="modal-body">
                <p id="msn"></p>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-danger" id="btDeletar" data-dismiss="modal">Deletar</button>
            </div>
        </div>
    </div>
</div>


<script>
    function registrarTransacao() {
        window.location.href = "../Transacao/Registrar";

    }

    function ExcluirTransacao(id) {
        $(document).ready(function () {
            $("#myModal").modal({ backdrop: "static" });
            document.getElementById("msn").innerHTML = "Deseja mesmo deletar este registro " + '<strong>' + id + '</strong>' + " ?";


            $("#btDeletar").click(function () {
                window.location.href = "../Transacao/ExcluirTransacao/" + id;
            });
        });
        $("#myModal").hide();
    }

    function editarTransacao(id) {
        window.location.href = "../Transacao/Registrar/" + id;

    }

    function DetalhesTransacao(id) {
       
        $(document).ready(function () {
            
         
            
            window.location.href = "../Transacao/DetalhesTransacao/" + id;
        });
       
        $("#modalDetalhes").modal({ backdrop: "static" });
       

    }

</script>

MyFinance/Views/Transacao/Registrar.cshtml
@model TransacaoModel


@{
    var vData = "";
    var vDescricao = "";
    var vTipo = "";
    var vValor = 0.0;
    var vId = 0;
    var vContaId = 0;
    var vPlanoContaId = 0;

    try
    {
        vId = int.Parse(@ViewBag.Registro.Id.ToString());
        vData = DateTime.Parse(@ViewBag.Registro.Data.ToString()).ToString("yyyy-MM-dd");

        vTipo = @ViewBag.Registro.Tipo.ToString();


        vContaId = int.Parse(@ViewBag.Registro.Conta_Id.ToString());
        vPlanoContaId = int.Parse(@ViewBag.Registro.Plano_Conta_Id.ToString());

        vValor = double.Parse(@ViewBag.Registro.Valor.ToString());
        vDescricao = @ViewBag.Registro.Descricao.ToString();

    }
    catch
    {

    }

}

<h2>Transacão</h2>

<form asp-controller="Transacao" asp-action="Registrar">
    <input type="hidden" asp-for="Id" value="@vId" />

    <div>
        <label>Data</label>
        <input type="date" class="form-control" asp-for="Data" value="@vData" />
        <span asp-validation-for="Data" class="text-danger"></span>
    </div>

 
    <div class="form-group">
        <label>Tipo</label>

        @{


            if (vTipo == "R")
            {
                <div class="radio"><label><input type="radio" asp-for="Tipo" value="R" checked />Receita</label></div>
                <div class="radio"><label><input type="radio" asp-for="Tipo" value="D" unchecked />Despesa</label></div>

            }
            else
            {
                <div class="radio"><label><input type="radio" asp-for="Tipo" value="R" unchecked />Receita</label></div>
                <div class="radio"><label><input type="radio" asp-for="Tipo" value="D" checked />Despesa</label></div>

            }
        }
        </div>

        <div>
            <label>Valor</label>
            <input type="number" class="form-control" asp-for="Valor" value="@vValor" />
            <span asp-validation-for="Valor" class="text-danger"></span>
        </div>

        <div>
            <label>Historico</label>
            <!--<textarea rows="5" class="form-control" asp-for="Descricao" value="@vDescricao"></textarea>-->
            @Html.TextArea("Descricao", vDescricao, new { @class = "form-control" })
            <span asp-validation-for="Descricao" class="text-danger"></span>
        </div>

        <br />

        <div class="form-group">
            <label>Contas</label>
            <select asp-for="Conta_Id" class="form-control">
                @{
                    foreach (var item in (List<ContaModel>)ViewBag.ListaContas)
                    {
                        if (item.Id.ToString() == vContaId.ToString())
                        {
                            <option selected value="@item.Id.ToString()">@item.Nome.ToString()</option>

                        }
                        else
                        {

                            <option value="@item.Id.ToString()">@item.Nome.ToString()</option>
                        }

                    }
                }
            </select>
        </div>

        <br />

        <div class="form-group">
            <label>Plano Conta</label>
            <select asp-for="Plano_Conta_Id" class="form-control">
                @{
                    foreach (var item in (List<PlanoContasModel>)ViewBag.ListaPlanoConta)
                    {
                        if (item.Id.ToString() == vPlanoContaId.ToString())
                        {
                            <option selected value="@item.Id.ToString()">@item.Descricao.ToString()</option>

                        }
                        else
                        {
                            <option value="@item.Id.ToString()">@item.Descricao.ToString()</option>

                        }

                    }
                }
            </select>
        </div>

        <button type="submit" class="btn btn-success">Salvar</button>
        <button type="reset" class="btn ">Cancelar</button>
</form>